import "./globals.css";
import { Toaster } from 'sonner';
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "FreeApiHub",
  description: "Generated by create next app",
  icons: "./vercel.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class">
        <Toaster richColors theme="dark"/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
